#!/bin/sh

# set the game directory
if [ ! -f /config/Dolphin.ini ]; then
    tee /config/Dolphin.ini >/dev/null<<EOF
[General]
ISOPaths = 2
RecursiveISOPaths = True
ISOPath0 = /gc
ISOPath1 = /wii
UseGameCovers = True
UseDiscordPresence = False
[Interface]
PauseOnFocusLost = True
[Core]
EnableCheats = True
[Input]
BackgroundInput = True
[DSP]
Backend = Pulse

EOF
fi

exec "$(which dolphin-emu)" "$@"
