#!/bin/sh

try_fetch_bios() {
    # abort if /bios contains any *.bin files
    if [ "$(ls /bios/*.bin 2>/dev/null | wc -l)" != "0" ]; then
        return
    fi

    echo "[WARN] No BIOS files found in /bios" >&2

    # abort if not explicitly told to fetch bios files
    if [ -z "${BIOS_ZIP:-}" ]; then
        return
    fi

    echo "[WARN] BIOS files will be downloaded from $BIOS_ZIP" >&2
    echo "[WARN] Sleeping for 5 seconds, press CTRL+C now to abort ..." >&2
    sleep 5

    wget -qO- "$BIOS_ZIP" > /tmp/ps2_bios.zip

    # verify checksum
    if [ ! -z "${BIOS_CHECKSUM:-}" ]; then
        checksum=$(sha256sum -b /tmp/ps2_bios.zip | awk '{ print $1 }')

        if [ "$checksum" != "$BIOS_CHECKSUM" ]; then
            echo "[ERR] Checksum mismatch /tmp/ps2_bios.zip $checksum" >&2
            rm -f /tmp/ps2_bios.zip 2>/dev/null

            return
        fi
    fi

    unzip -Lnq /tmp/ps2_bios.zip -d /bios
    rm -f /tmp/ps2_bios.zip 2>/dev/null

    echo "[WARN] BIOS files downloaded" >&2
}

# download bios files if /bios is empty and $ALLOW_BIOS_DOWNLOAD === 1
try_fetch_bios

mkdir -p /data/inis

# PCSX2 defaults
if [ ! -f /data/inis/PCSX2.ini ]; then
    tee /data/inis/PCSX2.ini >/dev/null<<EOF
[UI]
SettingsVersion = 1
Theme = darkfusion
SetupWizardIncomplete = false

[Folders]
Bios = /bios
Snapshots = /data/snaps
Savestates = /data/sstates
MemoryCards = /data/memcards
Logs = /data/logs
Cheats = /data/cheats
Patches = /data/patches
Cache = /data/cache
Textures = /data/textures
InputProfiles = /data/inputprofiles
Videos = /data/videos
Covers = /data/covers

[AutoUpdater]
CheckAtStartup = false

[GameList]
Paths = /games

EOF
fi

# automatically use bios with the latest timestamp if not set
if grep -qE "^BIOS=$" /data/inis/PCSX2.ini; then
    bios=$(cd /bios; ls -1t *.bin 2>/dev/null | head -n1)

    if [ ! -z "$bios" ]; then
        echo "[WARN] BIOS is not set defaulting to $bios" >&2
        sed -i -E "s/^BIOS=/BIOS=$bios/" /data/inis/PCSX2.ini
    else
        echo "[ERR] PCSX2 will not function without a BIOS" >&2
    fi
fi

# start PCSX2
exec "$(which pcsx2-qt)" "$@"
