#!/bin/sh

# create the default profile
if [ ! -f /data/firefox/profiles.ini ]; then
    CONTAINER_ID_SHORT=$(awk -F':' '$2 == "pids" { print $3 }' /proc/1/cgroup \
        | awk -F'/' '{ print $3 }' \
        | sed -E "s/^(.{8}).*/\1/")

    PROFILE_NAME=$CONTAINER_ID_SHORT.default

    # create profile directory
    mkdir -p "/data/firefox/$PROFILE_NAME"

    # create profiles.ini
    tee /data/firefox/profiles.ini >/dev/null<<EOF
[General]
StartWithLastProfile=1

[Profile0]
Name=default
IsRelative=1
Path=$PROFILE_NAME
Default=1

EOF

    # set default user preferences
    USER_FILE="/data/firefox/$PROFILE_NAME/user.js"
    echo 'user_pref("general.autoScroll", true);' >> "$USER_FILE"

    # force open gl if nvidia card detected (fragile)
    if ls /dev/nvidiactl 2>/dev/null | grep -q "."; then
        echo 'user_pref("layers.acceleration.force-enabled", true);' >> "$USER_FILE"
    fi
fi

# start firefox
exec "$(which firefox)" "$@"
