#!/bin/sh

# export XDG_RUNTIME_DIR
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"

# export DBUS_SESSION_BUS_ADDRESS
if [ -z "${DBUS_SESSION_BUS_ADDRESS:-}" -a -S "$XDG_RUNTIME_DIR/bus" ]; then

    export DBUS_SESSION_BUS_ADDRESS="unix:path=$XDG_RUNTIME_DIR/bus"
fi

# make directories writeable
sudo chown $(id -u):$(id -g) /config /cache "$XDG_RUNTIME_DIR"
