#!/bin/sh

# make directories writeable
sudo chown $(id -u):$(id -g) "/saves" "/config"

# ini defaults
if [ ! -f /config/yabause.ini ]; then
    tee /config/yabause.ini >/dev/null<<EOF
[0.9.11]
General\SaveStates=/saves

EOF
fi

# start yabasanshiro
exec "$(which yabause)" "$@"
