#!/bin/sh

# hdpi.ini defaults
if [ ! -f /config/hdpi.ini ]; then
    tee /config/hdpi.ini >/dev/null<<EOF
[hdpisupport]
auto_scale=true
enabled=true
pixel_ratio=2
scale_factor=1

EOF
fi

# smplayer.ini defaults
if [ ! -f /config/smplayer.ini ]; then
    tee /config/smplayer.ini >/dev/null<<EOF
[%General]
add_blackborders_on_fullscreen=false
alang="eng,jap"
audio_equalizer=0, 0, 0, 0, 0, 0, 0, 0, 0, 0
autoload_m4a=true
autoq=6
autosync_factor=100
autosync=true
config_version=5
disable_screensaver=true
file_settings_method=hash
global_audio_equalizer=true
global_volume=true
mc_value=0
min_step=4
mute=false
osd_bar_pos=80
osd_delay=5000
osd_fractions=false
osd_scale=1
osd_show_filename_duration=2000
osd=1
remember_media_settings=true
remember_stream_settings=true
remember_time_pos=true
slang=
softvol_max=150
subfont_osd_scale=3
tablet_mode=false
use_audio_equalizer=false
use_direct_rendering=false
use_double_buffer=true
use_hwac3=false
use_mc=false
use_scaletempo=-1
use_slices=true
use_soft_video_eq=false
use_soft_vol=true
vdpau_disable_video_filters=true
vdpau_ffh264vdpau=true
vdpau_ffhevcvdpau=false
vdpau_ffmpeg12vdpau=true
vdpau_ffodivxvdpau=false
vdpau_ffvc1vdpau=true
vdpau_ffwmv3vdpau=true
volume=100
wayland_workarounds=false

[advanced]
actions_to_run=
autosave_mplayer_log=false
change_video_equalizer_on_startup=true
correct_pts=-1
emulate_mplayer_ab_section=false
log_filter=.*
log_mplayer=true
log_smplayer=true
monitor_aspect=
mplayer_additional_audio_filters=
mplayer_additional_options=
mplayer_additional_video_filters=
mplayer_log_saveto=
mplayer_osd_media_info=
mpv_osd_media_info=
prefer_ipv4=true
repaint_video_background=true
save_smplayer_log=false
show_tag_in_window_title=true
time_to_kill_player=5000
use_edl_files=true
use_idx=false
use_lavf_demuxer=false
use_mplayer_window=false
use_mpris2=true
use_native_open_dialog=true
use_pausing_keep_force=true
use_playlist_option=false
use_short_pathnames=false
verbose_log=false

[directories]
latest_dir=/videos
save_dirs=true

[floating_control]
activation_area=1
animated=false
display_in_compact_mode=true
hide_delay=3000
margin=0
width=100

[gui]
auto_add_to_playlist=false
gui=MpcGUI
iconset=Papirus
media_to_add_to_playlist=0
mouse_wheel_function=4
qt_style=GTK+

[instances]
single_instance_enabled=false

[mpc_gui]
toolbars_state=@ByteArray(\0\0\0\xff\0\0\x18@\xfd\0\0\0\x1\0\0\0\x3\0\0\0\0\0\0\0\0\xfc\x1\0\0\0\x1\xfb\0\0\0\x18\0p\0l\0\x61\0y\0l\0i\0s\0t\0\x64\0o\0\x63\0k\x2\0\0\0\0\0\0\0\0\0\0\0\x64\0\0\0\x1e\0\0\x3^\0\0\x1\xa0\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\x2\0\0\0\x3\0\0\0\x1\0\0\0\x1a\0\x63\0o\0n\0t\0r\0o\0l\0w\0i\0\x64\0g\0\x65\0t\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x3\0\0\0\x1\0\0\0\x1e\0t\0i\0m\0\x65\0s\0l\0i\0\x64\0\x65\0w\0i\0\x64\0g\0\x65\0t\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0)

[performance]
cache_auto=true
cache_for_audiocds=1024
cache_for_dvds=0
cache_for_files=2048
cache_for_streams=2048
cache_for_tv=3000
cache_for_vcds=1024
coreavc=false
frame_drop=false
h264_skip_loop_filter=1
hard_frame_drop=false
HD_height=720
hwdec=auto
threads=4

[streaming]
streaming_type=1
streaming\youtube\resolution=5
streaming\youtube\use_60fps=true
streaming\youtube\use_dash=true
streaming\youtube\yt_use_https_main=false
streaming\youtube\yt_user_agent="Mozilla/5.0 (X11; Linux x86_64; rv:5.0.1) Gecko/20100101 Firefox/5.0.1"
ytdl_quality=

[subtitles]
ass_line_spacing=0
autoload_sub=true
change_sub_scale_should_restart=-1
enable_ass_styles=true
enca_lang=
fast_load_sub=true
force_ass_styles=false
freetype_support=true
styles\backcolor\argb=ff000000
styles\backgroundcolor\argb=b4000000
styles\bold=false
styles\borderstyle=3
styles\fontname=Sans Serif
styles\fontsize=18
styles\halignment=2
styles\italic=false
styles\marginl=20
styles\marginr=20
styles\marginv=8
styles\outline=0.3
styles\outlinecolor\argb=ff000000
styles\primarycolor\argb=ffffffff
styles\shadow=1
styles\valignment=0
sub_visibility=true
subcp=ISO-8859-1
subfuzziness=1
subtitles_on_screenshots=false
use_ass_subtitles=true
use_enca=false
use_forced_subs_only=false
user_forced_ass_style=

[update_checker]
enabled=false

EOF
fi

# start smplayer
exec "$(which smplayer)" "$@"
