#!/bin/sh

# smplayer.ini defaults
if [ ! -f /config/smplayer.ini ]; then
    tee /config/smplayer.ini >/dev/null<<EOF
[%General]
config_version=5
remember_media_settings=true
remember_time_pos=true
remember_stream_settings=true
alang="eng,jap"
slang=
use_direct_rendering=false
use_double_buffer=true
use_soft_video_eq=false
use_slices=true
autoq=6
add_blackborders_on_fullscreen=false
disable_screensaver=true
vdpau_ffh264vdpau=true
vdpau_ffmpeg12vdpau=true
vdpau_ffwmv3vdpau=true
vdpau_ffvc1vdpau=true
vdpau_ffodivxvdpau=false
vdpau_ffhevcvdpau=false
vdpau_disable_video_filters=true
use_soft_vol=true
softvol_max=150
use_scaletempo=-1
use_hwac3=false
use_audio_equalizer=false
global_volume=true
volume=100
mute=false
global_audio_equalizer=true
audio_equalizer=0, 0, 0, 0, 0, 0, 0, 0, 0, 0
autosync=true
autosync_factor=100
use_mc=false
mc_value=0
autoload_m4a=true
min_step=4
osd=1
osd_scale=1
subfont_osd_scale=3
osd_delay=5000
osd_fractions=false
osd_bar_pos=80
osd_show_filename_duration=2000
file_settings_method=hash
tablet_mode=false

[performance]
frame_drop=false
hard_frame_drop=false
coreavc=false
h264_skip_loop_filter=1
HD_height=720
threads=4
hwdec=auto
cache_auto=true
cache_for_files=2048
cache_for_streams=2048
cache_for_dvds=0
cache_for_vcds=1024
cache_for_audiocds=1024
cache_for_tv=3000

[subtitles]
subcp=ISO-8859-1
use_enca=false
enca_lang=
subfuzziness=1
autoload_sub=true
use_ass_subtitles=true
enable_ass_styles=true
ass_line_spacing=0
use_forced_subs_only=false
sub_visibility=true
subtitles_on_screenshots=false
change_sub_scale_should_restart=-1
fast_load_sub=true
styles\fontname=Sans Serif
styles\fontsize=18
styles\primarycolor\argb=ffffffff
styles\backcolor\argb=ff000000
styles\outlinecolor\argb=ff000000
styles\backgroundcolor\argb=b4000000
styles\bold=false
styles\italic=false
styles\halignment=2
styles\valignment=0
styles\borderstyle=3
styles\outline=0.3
styles\shadow=1
styles\marginl=20
styles\marginr=20
styles\marginv=8
force_ass_styles=false
user_forced_ass_style=
freetype_support=true

[advanced]
use_mplayer_window=false
monitor_aspect=
use_idx=false
use_lavf_demuxer=false
mplayer_additional_options=
mplayer_additional_video_filters=
mplayer_additional_audio_filters=
log_mplayer=true
verbose_log=false
autosave_mplayer_log=false
mplayer_log_saveto=
log_smplayer=true
log_filter=.*
save_smplayer_log=false
repaint_video_background=true
use_edl_files=true
use_playlist_option=false
prefer_ipv4=true
use_short_pathnames=false
change_video_equalizer_on_startup=true
use_pausing_keep_force=true
correct_pts=-1
actions_to_run=
show_tag_in_window_title=true
time_to_kill_player=5000
use_mpris2=true
mpv_osd_media_info=
mplayer_osd_media_info=
emulate_mplayer_ab_section=false
use_native_open_dialog=true

[gui]
qt_style=GTK+
mouse_wheel_function=4
iconset=Papirus
gui=MpcGUI
auto_add_to_playlist=false
media_to_add_to_playlist=0

[streaming]
streaming_type=1
ytdl_quality=
streaming\youtube\resolution=5
streaming\youtube\yt_user_agent="Mozilla/5.0 (X11; Linux x86_64; rv:5.0.1) Gecko/20100101 Firefox/5.0.1"
streaming\youtube\yt_use_https_main=false
streaming\youtube\use_dash=true
streaming\youtube\use_60fps=true

[directories]
latest_dir=/videos
save_dirs=true

[instances]
single_instance_enabled=false

[floating_control]
margin=0
width=100
animated=false
display_in_compact_mode=true
activation_area=1
hide_delay=3000

[update_checker]
enabled=false

EOF
fi

# start smplayer
exec "$(which smplayer)" "$@"
