#!/bin/sh

# create a dummy machine-id based on the container id to reduce
# errors when running chromium, this is not a real machine id
# and will not work with pulseaudio on the host, machine-id
# should be mounted from the host instead so that the soundcard
# can be shared, e.g.
#
# docker run \
#   -v /etc/machine-id:/etc/machine-id:ro \
#   -v /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro \
#   ...

if [ ! -f /etc/machine-id ]; then
    awk -F':' '$2 == "pids" { print $3 }' /proc/1/cgroup \
        | awk -F'/' '{ print $3 }' \
        | sed -E "s/^(.{32}).*/\1/" > /etc/machine-id
fi

if [ ! -f /var/lib/dbus/machine-id ]; then
    mkdir -p /var/lib/dbus
    ln -s /etc/machine-id /var/lib/dbus/machine-id
fi
