---
version: "2.1"

services:
  chromium:
    image: andrewmackrodt/chromium
    privileged: true
    network_mode: host
    devices:
      - /dev/snd
    environment:
      # host UID/GID mapping
      - PUID=${UID:-1000}
      - GUID=${UID:-1000}
      # x11
      - DISPLAY=unix$DISPLAY
      # optional, this is the default
      - XDG_RUNTIME_DIR=/run/user/${PUID:-1000}
      # optional, required if pulseaudio not configured
      - ALSA_PCM=${ALSA_PCM:-dmix:CARD=NVidia,DEV=8}
    volumes:
      # x11
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      # runtime
      - /dev/shm:/dev/shm
      # pulseaudio
      - /etc/machine-id:/etc/machine-id:ro
      - $HOME/.config/pulse:/home/ubuntu/.config/pulse:ro
      - /run/user/${PUID:-1000}/pulse:/run/user/${PUID:-1000}/pulse:ro
      # dbus (optional, less errors in output when provided)
      - /run/dbus:/run/dbus:ro
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
      # timezone (optional)
      - /etc/localtime:/etc/localtime:ro
      # chromium
      - $HOME/Downloads:/downloads
      - data:/data

volumes:
  data:
